FROM upstream

COPY target/x86_64-unknown-linux-musl/release/secret-loader /bin/secret-loader
COPY target/x86_64-unknown-linux-musl/release/check-http /bin/check-http

ENTRYPOINT [ "/bin/secret-loader" ]
CMD [ "/twilight-http-proxy" ]
