FROM scratch

COPY target/x86_64-unknown-linux-musl/release/secret-loader /bin/secret-loader
COPY target/x86_64-unknown-linux-musl/release/tulpje-handler /bin/tulpje-handler

ENTRYPOINT [ "/bin/secret-loader" ]
CMD [ "/bin/tulpje-handler" ]
